language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: XiKysuC0OJfT3EwnilIj/YYofl2ln/mZy10XQIQp+Hdmy/ECaBhmtA9/SqK7aSv3GkbIlAD3yaMadzNyXVVtTwLKKXeFux1ksHuITNtmXOV8R1EOr2h0sWfk8qbf+9LIq9PRa8DDTYboXP1GSMYtp5n1it0l1UcKBO+4e3EMQJ0=
  - secure: rHqB+jH6CBtdlFfcxOrMaxDR8F6bukRcsGck0y0R0PsOzev1SojQIe+xpSvnoV/ESwSMB4vXKyafRWne60Tbt6TOI3K9nLU5xTS8qMsuRtqWVXaLh0iPcDUtll6BmFQx9MncPKmakNo8xyKxD0GBFhPD/pbF+VfsYQL+J6WoOow=
